"""empty message

Revision ID: 1e96f55a362a
Revises: ed9252290437
Create Date: 2024-04-22 17:46:25.058652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e96f55a362a'
down_revision = 'ed9252290437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
